import: definition.yaml

concurrency:
  task:
    ta1-std: 6
  agent:
    gpt-5-mini: 5
    gemini-3.1-flash-lite: 5
    claude-haiku-4.5: 5
    xiaomi-mimo-v2-pro: 3
    z-ai-glm-5: 3
    gemma-3-27b-it: 2
    nemotron-3-nano-30b: 3
    gpt-oss-20b: 2

assignments:
  - agent:
      - gpt-5-mini
      - gemini-3.1-flash-lite
      - claude-haiku-4.5
      - xiaomi-mimo-v2-pro
      - z-ai-glm-5
      - gemma-3-27b-it
      - nemotron-3-nano-30b
      - gpt-oss-20b
    task:
      - ta1-std

output: "outputs_TA1/MedAgentBenchv1"
