assignments:
- agent: gpt-5-mini
  task: ta1-std
- agent: gpt-5-mini
  task: ta1-std
- agent: gpt-5-mini
  task: ta1-std
- agent: gpt-5-mini
  task: ta1-std
- agent: gpt-5-mini
  task: ta1-std
- agent: gpt-5-mini
  task: ta1-std
- agent: gpt-5-mini
  task: ta1-std
- agent: gpt-5-mini
  task: ta1-std
concurrency:
  agent:
    claude-haiku-4.5: 5
    gemini-3.1-flash-lite: 5
    gemma-3-27b-it: 2
    gpt-5-mini: 5
    gpt-oss-20b: 2
    nemotron-3-nano-30b: 3
    xiaomi-mimo-v2-pro: 3
    z-ai-glm-5: 3
  task:
    ta1-std: 20
definition:
  agent:
    claude-haiku-4.5:
      module: src.client.agents.HTTPAgent
      parameters:
        body:
          max_tokens: 2048
          model: anthropic/claude-haiku-4.5
          temperature: 0
        headers:
          Authorization: Bearer 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
          Content-Type: application/json
          HTTP-Referer: http://localhost
          X-Title: MedAgentBench
        name: claude-haiku-4.5
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        return_format: '{response[choices][0][message][content]}'
        url: https://openrouter.ai/api/v1/chat/completions
    gemini-3.1-flash-lite:
      module: src.client.agents.HTTPAgent
      parameters:
        body:
          max_tokens: 2048
          model: google/gemini-3.1-flash-lite-preview
          temperature: 0
        headers:
          Authorization: Bearer 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
          Content-Type: application/json
          HTTP-Referer: http://localhost
          X-Title: MedAgentBench
        name: gemini-3.1-flash-lite
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        return_format: '{response[choices][0][message][content]}'
        url: https://openrouter.ai/api/v1/chat/completions
    gemma-3-27b-it:
      module: src.client.agents.HTTPAgent
      parameters:
        body:
          max_tokens: 2048
          model: google/gemma-3-27b-it
          temperature: 0
        headers:
          Authorization: Bearer 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
          Content-Type: application/json
          HTTP-Referer: http://localhost
          X-Title: MedAgentBench
        name: gemma-3-27b-it
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        return_format: '{response[choices][0][message][content]}'
        url: https://openrouter.ai/api/v1/chat/completions
    gpt-5-mini:
      module: src.client.agents.HTTPAgent
      parameters:
        body:
          max_tokens: 2048
          model: openai/gpt-5-mini
          temperature: 0
        headers:
          Authorization: Bearer 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
          Content-Type: application/json
          HTTP-Referer: http://localhost
          X-Title: MedAgentBench
        name: gpt-5-mini
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        return_format: '{response[choices][0][message][content]}'
        url: https://openrouter.ai/api/v1/chat/completions
    gpt-oss-20b:
      module: src.client.agents.HTTPAgent
      parameters:
        body:
          max_tokens: 2048
          model: gpt-oss-20b
          temperature: 0
        headers:
          Authorization: Bearer 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
          Content-Type: application/json
          HTTP-Referer: http://localhost
          X-Title: MedAgentBench
        name: gpt-oss-20b
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        return_format: '{response[choices][0][message][content]}'
        url: https://openrouter.ai/api/v1/chat/completions
    nemotron-3-nano-30b:
      module: src.client.agents.HTTPAgent
      parameters:
        body:
          max_tokens: 2048
          model: nvidia/nemotron-3-nano-30b-a3b
          temperature: 0
        headers:
          Authorization: Bearer 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
          Content-Type: application/json
          HTTP-Referer: http://localhost
          X-Title: MedAgentBench
        name: nemotron-3-nano-30b
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        return_format: '{response[choices][0][message][content]}'
        url: https://openrouter.ai/api/v1/chat/completions
    xiaomi-mimo-v2-pro:
      module: src.client.agents.HTTPAgent
      parameters:
        body:
          max_tokens: 2048
          model: xiaomi/mimo-v2-pro
          temperature: 0
        headers:
          Authorization: Bearer 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
          Content-Type: application/json
          HTTP-Referer: http://localhost
          X-Title: MedAgentBench
        name: xiaomi-mimo-v2-pro
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        return_format: '{response[choices][0][message][content]}'
        url: https://openrouter.ai/api/v1/chat/completions
    z-ai-glm-5:
      module: src.client.agents.HTTPAgent
      parameters:
        body:
          max_tokens: 2048
          model: z-ai/glm-5
          temperature: 0
        headers:
          Authorization: Bearer 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
          Content-Type: application/json
          HTTP-Referer: http://localhost
          X-Title: MedAgentBench
        name: z-ai-glm-5
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        return_format: '{response[choices][0][message][content]}'
        url: https://openrouter.ai/api/v1/chat/completions
  task:
    ta1-std:
      module: src.client.TaskClient
      parameters:
        concurrency: 1
        controller_address: http://localhost:5000/api
        data_file: data/medagentbench/test_data_ta1.json
        fhir_api_base: http://localhost:8080/fhir/
        func_file: data/medagentbench/funcs_v1.json
        max_round: 8
        name: ta1-std
output: outputs_TA1/MedAgentBenchv1
