controller: "http://localhost:5100/api"

definition:
  import: tasks/task_assembly.yaml

start:
  # TA1 / TA3 tasks
  ta1-std: 2
  ta3-std: 2

  # NO-CALCULATOR MODE (tasks that compute scores manually)
  meld-std: 2
  fib4-std: 2
  child-pugh-std: 2
  
  # WITH CALCULATOR MODE (tasks that use calculator API)
  meld-calc: 2
  fib4-calc: 2
  child-pugh-calc: 2